GET http://localhost:3600/employees/

### 
POST http://localhost:3600/employees
Content-Type: application/json

{
        "firstname": "Thala",
        "lastname": "Dhoni"
}


###
DELETE http://localhost:3600/employees
Content-Type: application/json

{
        "id":4
}